export enum TokenType {
  Abstract = 'ABSTRACT',
  AmpersandAmpersand = 'AMPERSAND_AMPERSAND',
  AmpersandAmpersandEquals = 'AMPERSAND_AMPERSAND_EQUALS',
  BangEqual = 'BANG_EQUAL',
  Class = 'CLASS',
  Colon = 'COLON',
  Comma = 'COMMA',
  Constructor = 'CONSTRUCTOR',
  Do = 'DO',
  Dot = 'DOT',
  Ellipsis = 'ELLIPSIS',
  EOF = 'EOF',
  EqualEqual = 'EQUAL_EQUAL',
  Equals = 'EQUALS',
  Except = 'EXCEPT',
  Export = 'EXPORT',
  Extends = 'EXTENDS',
  Finally = 'FINALLY',
  For = 'FOR',
  From = 'FROM',
  Function = 'FUNCTION',
  Greater = 'GREATER',
  GreaterEquals = 'GREATER_EQUALS',
  Import = 'IMPORT',
  Implements = 'IMPLEMENTS',
  Identifier = 'IDENTIFIER',
  LeftBrace = 'LEFT_BRACE',
  LeftBracket = 'LEFT_BRACKET',
  LeftParen = 'LEFT_PAREN',
  Less = 'LESS',
  LessEquals = 'LESS_EQUALS',
  Minus = 'MINUS',
  MinusEquals = 'MINUS_EQUALS',
  New = 'NEW',
  Null = 'NULL',
  Number = 'NUMBER',
  Of = 'OF',
  Override = 'OVERRIDE',
  Percent = 'PERCENT',
  PercentEquals = 'PERCENT_EQUALS',
  PipePipe = 'PIPE_PIPE',
  PipePipeEquals = 'PIPE_PIPE_EQUALS',
  Plus = 'PLUS',
  PlusEquals = 'PLUS_EQUALS',
  Private = 'PRIVATE',
  Protected = 'PROTECTED',
  Public = 'PUBLIC',
  Question = 'QUESTION',
  QuestionQuestion = 'QUESTION_QUESTION',
  QuestionQuestionEquals = 'QUESTION_QUESTION_EQUALS',
  Return = 'RETURN',
  RightBrace = 'RIGHT_BRACE',
  RightBracket = 'RIGHT_BRACKET',
  RightParen = 'RIGHT_PAREN',
  Semicolon = 'SEMICOLON',
  Slash = 'SLASH',
  SlashEquals = 'SLASH_EQUALS',
  Star = 'STAR',
  StarEquals = 'STAR_EQUALS',
  Static = 'STATIC',
  String = 'STRING',
  Super = 'SUPER',
  This = 'THIS',
  Throw = 'THROW',
  Try = 'TRY',
  Val = 'VAL',
  Var = 'VAR',
  Virtual = 'VIRTUAL',
  While = 'WHILE',
}

export type Token = {
  column: number;
  lexeme: string;
  line: number;
  type: TokenType;
};
