export enum TokenType {
  AmpersandAmpersand = 'AMPERSAND_AMPERSAND',
  AmpersandAmpersandEquals = 'AMPERSAND_AMPERSAND_EQUALS',
  BangEqual = 'BANG_EQUAL',
  Colon = 'COLON',
  Comma = 'COMMA',
  Do = 'DO',
  EOF = 'EOF',
  EqualEqual = 'EQUAL_EQUAL',
  Equals = 'EQUALS',
  Export = 'EXPORT',
  For = 'FOR',
  From = 'FROM',
  Function = 'FUNCTION',
  Greater = 'GREATER',
  GreaterEquals = 'GREATER_EQUALS',
  Import = 'IMPORT',
  Identifier = 'IDENTIFIER',
  LeftBrace = 'LEFT_BRACE',
  LeftBracket = 'LEFT_BRACKET',
  LeftParen = 'LEFT_PAREN',
  Less = 'LESS',
  LessEquals = 'LESS_EQUALS',
  Minus = 'MINUS',
  MinusEquals = 'MINUS_EQUALS',
  Null = 'NULL',
  Number = 'NUMBER',
  Of = 'OF',
  Percent = 'PERCENT',
  PercentEquals = 'PERCENT_EQUALS',
  PipePipe = 'PIPE_PIPE',
  PipePipeEquals = 'PIPE_PIPE_EQUALS',
  Plus = 'PLUS',
  PlusEquals = 'PLUS_EQUALS',
  Question = 'QUESTION',
  QuestionQuestion = 'QUESTION_QUESTION',
  QuestionQuestionEquals = 'QUESTION_QUESTION_EQUALS',
  Return = 'RETURN',
  RightBrace = 'RIGHT_BRACE',
  RightBracket = 'RIGHT_BRACKET',
  RightParen = 'RIGHT_PAREN',
  Semicolon = 'SEMICOLON',
  Slash = 'SLASH',
  SlashEquals = 'SLASH_EQUALS',
  Star = 'STAR',
  StarEquals = 'STAR_EQUALS',
  String = 'STRING',
  Val = 'VAL',
  Var = 'VAR',
  While = 'WHILE',
}

export type Token = {
  column: number;
  lexeme: string;
  line: number;
  type: TokenType;
};
